### ISSUE TITLE
About running error

### ISSUE THREAD

**Issue by mountains-high** [kozistr/gan-metrics#2]
Hello, 
Thank you for your fine work

Could you help me to solve this issue, please? 
```
ImportError: cannot import name 'IMAGENET_NORMALIZE' from partially initialized module 'data' (most likely due to a circular import) 
```
I got this error message while running "python3 __main__.py" and "python3 -m metrics"

Thank you

**Comment by kozistr** [comment]
oh maybe I import package circularly : (. It's because like, `in script A, from B import sth / in script B, from A import sth`

But, i have no resources these days so can't sure when it'll be fixed :( sorry for that

Thanks in advance
